name: deb-package
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential debhelper devscripts
    - name: Build package
      run: |
        cd ${{ github.event.repository.name }}
        dpkg-buildpackage -us -uc
        cd ..
        lintian *.deb
    - name: Archive package
      uses: actions/upload-artifact@v4
      with:
        path: |
          *.deb
