name: FreeBSD-vm

on:
  workflow_dispatch:
  push:
    tags:
      - v**

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y bash
          pkg install -y gmake
        run: |
          gmake test
          gmake install PREFIX="$PWD/_install"
          ( cd "$PWD/_install" && tar czf ../FreeBSD.tar.gz . )
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: FreeBSD.tar.gz
