name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile
      run: make

    - name: Run test
      run: make test

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
