name: OpenBSD-vm

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in OpenBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg_add bash
          pkg_add gmake
        run: |
          gmake test
          gmake install PREFIX="$PWD/_install"
          ( cd "$PWD/_install" && tar czf ../OpenBSD.tar.gz . )
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: OpenBSD.tar.gz
