name: pkg-package
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pacman -Sy --noconfirm namcap
    - name: Build package
      run: |
        chown -R nobody .
        runuser -u nobody -- makepkg -s
        runuser -u nobody -- namcap *.pkg.tar.*
    - name: Archive package
      uses: actions/upload-artifact@v4
      with:
        path: |
          *.pkg.tar.*
